# Generated by Django 6.0 on 2025-12-04 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='short_description',
            field=models.CharField(default='', max_length=100),
        ),
    ]
